services:
  - type: web
    name: pagina-generar-equipos  
    runtime: python
    region: oregon  
    branch: main  
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  
    envVars:
  - key: SECRET_KEY
    generateValue: true  
  - key: DATABASE_URL
    fromDatabase: true  
      - key: PYTHON_VERSION
        value: 3.9.13  