services:
  - type: web
    name: pagina-generar-equipos
    env: python
    python:
      version: 3.9.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: pagina-generar-equipos-db
          type: postgres
  - key: SECRET_KEY
    generateValue: true  
  - key: DATABASE_URL
    fromDatabase: true  