"""eliminar campo posicion de jugadores

Revision ID: 07f4a45312f0
Revises: 1f7137a43ae2
Create Date: 2025-04-24 13:33:23.978875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f4a45312f0'
down_revision = '1f7137a43ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
