"""añadir campo posicion a jugadores

Revision ID: 1f7137a43ae2
Revises: 
Create Date: 2025-04-24 13:31:14.760154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7137a43ae2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicion', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jugador', schema=None) as batch_op:
        batch_op.drop_column('posicion')

    # ### end Alembic commands ###
